# Generated by Django 3.2 on 2022-09-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_alter_article_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('title', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('date', models.DateTimeField(max_length=250, verbose_name='Fecha')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('draft', models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['id'],
            },
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='name',
        ),
        migrations.AddField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='agent/', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='blog/', verbose_name='Imagen'),
        ),
    ]
