# Generated by Django 3.2 on 2022-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20220907_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='descripton',
            new_name='description',
        ),
        migrations.AddField(
            model_name='agent',
            name='url_facebook',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='agent',
            name='url_instagram',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='agent',
            name='url_linkedin',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='agent',
            name='url_twitter',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='agent',
            name='url_website',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Sitio web'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='media/agent/', verbose_name='Imagen'),
        ),
    ]
