# Generated by Django 3.2 on 2022-09-08 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_remove_agent_url_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='draft',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='nombre', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
