# Generated by Django 3.2 on 2022-09-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20220908_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='image',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de publicación'),
        ),
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha'),
        ),
    ]
