# Generated by Django 3.2 on 2022-09-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_auto_20220908_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='image/', verbose_name='Imagen'),
        ),
    ]
