# Generated by Django 3.2 on 2022-09-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='article/', verbose_name='Imagen'),
        ),
    ]
