# Generated by Django 3.2 on 2022-09-17 02:24

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Article_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('title', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Contenido')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('image_main', models.ImageField(blank=True, default='', null=True, upload_to='img_article/', verbose_name='Imagen principal')),
                ('image_01', models.ImageField(blank=True, default='', null=True, upload_to='img_article/', verbose_name='Imagen 01')),
                ('image_02', models.ImageField(blank=True, default='', null=True, upload_to='img_article/', verbose_name='Imagen 02')),
                ('image_03', models.ImageField(blank=True, default='', null=True, upload_to='img_article/', verbose_name='Imagen 03')),
                ('image_04', models.ImageField(blank=True, default='', null=True, upload_to='img_article/', verbose_name='Imagen 04')),
                ('image_05', models.ImageField(blank=True, default='', null=True, upload_to='img_article/', verbose_name='Imagen 05')),
                ('draft', models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador')),
                ('fk_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category_model', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['id'],
            },
        ),
    ]
