# Generated by Django 3.2 on 2022-09-07 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_agent_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='url_website',
        ),
    ]
