# Generated by Django 3.2 on 2022-09-17 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0002_alter_realstate_type_model_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate_model',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Dirección [*]'),
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='bath_qty',
            field=models.CharField(max_length=50, verbose_name='Cantidad de baños [*]'),
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='fk_tipo_inmueble',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='realstate.realstate_type_model', verbose_name='Tipo de inmueble [*]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Localización [*]'),
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre [*]'),
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='price',
            field=models.IntegerField(verbose_name='Precio [*]'),
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='room_qty',
            field=models.CharField(max_length=50, verbose_name='Cantidad de habitaciones [*]'),
        ),
        migrations.AlterField(
            model_name='realstate_type_model',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre [*]'),
        ),
    ]
