# Generated by Django 3.2 on 2022-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0004_realstate_model_fk_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realstate_model',
            options={'ordering': ['-date'], 'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AlterField(
            model_name='realstate_model',
            name='date',
            field=models.DateField(default='2022-09-17', verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
