# Generated by Django 3.2 on 2022-09-19 03:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0005_auto_20220918_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='realstate_model',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción'),
        ),
    ]
