# Generated by Django 3.2 on 2022-09-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0007_auto_20220919_0128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realstate_type_model',
            options={'ordering': ['-id'], 'verbose_name': 'Tipo de inmueble', 'verbose_name_plural': 'Tipos de inmueble'},
        ),
    ]
