# Generated by Django 3.2 on 2022-09-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0008_alter_realstate_type_model_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_Realstate_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre [*]')),
                ('email', models.EmailField(max_length=250, verbose_name='Email [*]')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto [*]')),
                ('message', models.TextField(verbose_name='Mensaje [*]')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('fk_realstate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realstate.realstate_model', verbose_name='Inmueble [*]')),
            ],
            options={
                'verbose_name': 'Mensaje desde inmueble',
                'verbose_name_plural': 'Mensajes desde inmuebles',
                'ordering': ['-created'],
            },
        ),
    ]
