# Generated by Django 3.2 on 2022-09-17 20:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_model',
            options={'ordering': ['id'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterField(
            model_name='article_model',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen [*]'),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='content',
            field=ckeditor.fields.RichTextField(default='null', verbose_name='Contenido [*]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_model',
            name='fk_categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.category_model', verbose_name='Categoría [*]'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article_model',
            name='image_main',
            field=models.ImageField(default='', upload_to='img_article/', verbose_name='Imagen principal [*]'),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='name',
            field=models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre [*]'),
        ),
        migrations.AlterField(
            model_name='article_model',
            name='title',
            field=models.CharField(default='Sin título', max_length=250, verbose_name='Título [*]'),
        ),
    ]
