# Generated by Django 3.2 on 2022-09-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_model_fk_agent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article_model',
            options={'ordering': ['-date'], 'verbose_name': 'Artículo', 'verbose_name_plural': 'Artículos'},
        ),
        migrations.AlterModelOptions(
            name='category_model',
            options={'ordering': ['-id'], 'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
    ]
