# Generated by Django 3.2 on 2022-09-17 02:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backend_Search_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Término de búsqueda')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Búsqueda Backend',
                'verbose_name_plural': 'Búsquedas Backend',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Frontend_Search_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Término de búsqueda')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Búsqueda Frontend',
                'verbose_name_plural': 'Búsquedas Frontend',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Message_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('subject', models.CharField(max_length=250, verbose_name='Asunto')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Page_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='sin_nombre', max_length=250, verbose_name='Nombre')),
                ('title', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('abstract', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Resumen')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Contenido')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha')),
                ('image_main', models.ImageField(blank=True, default='', null=True, upload_to='img_page/', verbose_name='Imagen principal')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['id'],
            },
        ),
    ]
