# Generated by Django 3.2 on 2022-09-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page_model',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
