# Generated by Django 3.2 on 2022-09-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20220917_1739'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message_Model',
            new_name='Message_Contact_Model',
        ),
        migrations.AlterModelOptions(
            name='backend_search_model',
            options={'ordering': ['-created'], 'verbose_name': 'Búsqueda Backend', 'verbose_name_plural': 'Búsquedas Backend'},
        ),
        migrations.AlterModelOptions(
            name='frontend_search_model',
            options={'ordering': ['-created'], 'verbose_name': 'Búsqueda Frontend', 'verbose_name_plural': 'Búsquedas Frontend'},
        ),
        migrations.AlterModelOptions(
            name='message_contact_model',
            options={'ordering': ['-created'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='page_model',
            options={'ordering': ['-date'], 'verbose_name': 'Página', 'verbose_name_plural': 'Páginas'},
        ),
    ]
