# Generated by Django 3.2 on 2022-09-28 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_agent_model_user'),
        ('panel', '0004_auto_20220923_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message_contact_model',
            options={'ordering': ['-created'], 'verbose_name': 'Mensaje Form Contacto', 'verbose_name_plural': 'Mensajes Form Contacto'},
        ),
        migrations.CreateModel(
            name='Message_Agent_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Asunto [*]')),
                ('message', models.TextField(verbose_name='Mensaje [*]')),
                ('agent_sender', models.CharField(max_length=250, verbose_name='Nombre [*]')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('agent_receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='agent.agent_model', verbose_name='Destinatario [*]')),
            ],
            options={
                'verbose_name': 'Mensaje Agente',
                'verbose_name_plural': 'Mensajes Agentes',
                'ordering': ['-created'],
            },
        ),
    ]
