# Generated by Django 3.2 on 2022-09-28 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0005_auto_20220928_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message_agent_model',
            options={'ordering': ['-created'], 'verbose_name': 'Mensaje de Agente', 'verbose_name_plural': 'Mensajes de Agentes'},
        ),
        migrations.AlterField(
            model_name='message_agent_model',
            name='agent_sender',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Remitente'),
        ),
    ]
