# Generated by Django 3.2 on 2022-10-06 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_message_agent_model_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message_agent_model',
            name='sender',
        ),
        migrations.AlterField(
            model_name='message_agent_model',
            name='agent_sender',
            field=models.CharField(default='1', max_length=3, verbose_name='Remitente [*]'),
            preserve_default=False,
        ),
    ]
