# Generated by Django 3.2 on 2022-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20221005_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='page_model',
            name='draft',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador'),
        ),
    ]
