# Generated by Django 3.2 on 2022-10-06 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_page_model_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message_agent_model',
            name='agent_sender',
            field=models.IntegerField(verbose_name='Remitente [*]'),
        ),
    ]
