# Generated by Django 3.2 on 2022-09-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_auto_20220917_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent_model',
            options={'ordering': ['-id'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
    ]
