# Generated by Django 3.2 on 2022-09-28 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agent', '0004_alter_agent_model_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_model',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='agent_model',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre [*]'),
        ),
    ]
