# Generated by Django 3.2 on 2022-10-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_alter_agent_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent_model',
            name='draft',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador'),
        ),
    ]
