# Generated by Django 3.2 on 2022-09-07 02:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('date', models.DateTimeField(blank=True, max_length=250, null=True, verbose_name='Fecha de publicación')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imágenes',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['id'], 'verbose_name': 'Agente', 'verbose_name_plural': 'Agentes'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['id'], 'verbose_name': 'Inmueble', 'verbose_name_plural': 'Inmuebles'},
        ),
        migrations.AddField(
            model_name='agent',
            name='descripton',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(max_length=50, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, verbose_name='Localización'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sin nombre', max_length=250, verbose_name='Nombre')),
                ('title', models.CharField(default='Sin título', max_length=250, verbose_name='Título')),
                ('subtitle', models.CharField(blank=True, max_length=250, null=True, verbose_name='Subtítulo')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='Resumen')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 7, 2, 20, 5, 287740), max_length=250, null=True, verbose_name='Fecha')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('draft', models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador')),
                ('fk_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Main.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
                'ordering': ['id'],
            },
        ),
    ]
