# Generated by Django 3.2 on 2022-09-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20220907_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='agent/', verbose_name='Imagen'),
        ),
    ]
