# Generated by Django 3.2 on 2022-09-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_image_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
