# Generated by Django 3.2 on 2022-09-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realstate_Type_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de inmueble',
                'verbose_name_plural': 'Tipos de inmueble',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Realstate_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('price', models.IntegerField(verbose_name='Precio')),
                ('location', models.CharField(max_length=50, verbose_name='Localización')),
                ('bath_qty', models.CharField(max_length=50, verbose_name='Cantidad de baños')),
                ('room_qty', models.CharField(max_length=50, verbose_name='Cantidad de habitaciones')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('image_main', models.ImageField(blank=True, default='', null=True, upload_to='img_realstate/', verbose_name='Imagen principal')),
                ('image_01', models.ImageField(blank=True, default='', null=True, upload_to='img_realstate/', verbose_name='Imagen carrusel 01')),
                ('image_02', models.ImageField(blank=True, default='', null=True, upload_to='img_realstate/', verbose_name='Imagen carrusel 02')),
                ('image_03', models.ImageField(blank=True, default='', null=True, upload_to='img_realstate/', verbose_name='Imagen carrusel 03')),
                ('image_04', models.ImageField(blank=True, default='', null=True, upload_to='img_realstate/', verbose_name='Imagen carrusel 04')),
                ('image_05', models.ImageField(blank=True, default='', null=True, upload_to='img_realstate/', verbose_name='Imagen carrusel 05')),
                ('draft', models.BooleanField(blank=True, default=True, null=True, verbose_name='Borrador')),
                ('fk_tipo_inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='realstate.realstate_type_model', verbose_name='Tipo de inmueble')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
                'ordering': ['id'],
            },
        ),
    ]
