# Generated by Django 3.2 on 2022-09-17 02:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realstate_type_model',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Descripción'),
        ),
    ]
