# Generated by Django 3.2 on 2022-09-17 02:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='img_agent/', verbose_name='Imagen')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Descripción')),
                ('url_twitter', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Twitter')),
                ('url_facebook', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Facebook')),
                ('url_linkedin', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Linkedin')),
                ('url_instagram', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['id'],
            },
        ),
    ]
