# Generated by Django 3.2 on 2022-09-17 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent_model',
            old_name='image',
            new_name='image_main',
        ),
    ]
